let videos=[
    {
        name:"Avatar-Telugu-2009(mp4)",
        thumbnail:"./thumbnails/Avatar-Telugu-2009(mp4).jpg",
        video:"videos/Avatar-Telugu-2009.mp4"
    },
    {
        name:"777-Charlie-Telugu-h1tfe-2022(mp4)",
        thumbnail:"./thumbnails/777-Charlie-Telugu-h1tfe-2022(mp4).jpg",
        video:"videos/777-Charlie-Telugu-h1tfe-2022.mp4"
    },
    {
        name:"Brahmastra-Part-One-Shiva-Telugu-n3sdf-2022(mp4)",
        thumbnail:"./thumbnails/Brahmastra-Part-One-Shiva-Telugu-n3sdf-2022(mp4).webp",
        video:"videos/Brahmastra-Part-One-Shiva-Telugu-n3sdf-2022.mp4"
    },
    {
        name:"Captain-Telugu-n2dsf-2022(mp4)",
        thumbnail:"./thumbnails/Captain-Telugu-n2dsf-2022(mp4).jpg",
        video:"videos/Captain-Telugu-n2dsf-2022.mp4"
    },
    {
        name:"Crazy-Fellow-Telugu-v2zsf-2022(mp4)",
        thumbnail:"./thumbnails/Crazy-Fellow-Telugu-v2zsf-2022(mp4).jpg",
        video:"videos/Crazy-Fellow-Telugu-v2zsf-2022.mp4"
    },
    {
        name:"Gandharwa-Telugu-shb6c-2022(mp4)",
        thumbnail:"./thumbnails/Gandharwa-Telugu-shb6c-2022(mp4).jpg",
        video:"videos/Gandharwa-Telugu-shb6c-2022.mp4"
    }
];